In [1]:
import numpy as np
X = np.array([1.1, 5.0, 2.8, 7.3])  # evidence for each choice
theta = 2.0                         # determinism parameter

ps = np.exp(X * theta)
ps /= np.sum(ps)

In [2]:
ps

array([4.07708656e-06, 9.95054552e-03, 1.22166230e-04, 9.89923211e-01])

In [3]:
np.amax(ps)#question 7

0.989923211165455

In [4]:
a = np.sum(ps)
a

1.0

In [5]:
np.log(0.1)

-2.3025850929940455

In [6]:
a=-(.3*np.log(0.5) + .5*np.log(0.25) + .2*np.log(0.25))

In [7]:
a

1.178350206951907

In [8]:
X = np.array([1.2, -2.5, 2.4, 3])
X = np.exp(X)
X = X/np.sum(X)

X


array([0.09620484, 0.00237852, 0.3194113 , 0.58200534])

In [9]:
np.sum(X)

1.0

In [11]:
import numpy as np

# X = (hours sleeping, hours studying), y = score on test
X = np.array((1.5, 2.5, 3), dtype=float)
b1 = np.array((0.1, 0.2, 0.3, 0.4), dtype=float)
b2 =np.array((5.2, 3.2, 4.3), dtype=float)
b3 = np.array((0.2, 0.45, 0.75, 0.55, 0.95), dtype=float)
#y = np.array(([92], [86], [89]), dtype=float)

# scale units
#X = X/np.amax(X, axis=0) # maximum of X array
#y = y/100 # max test score is 100

class Neural_Network(object):
  def __init__(self):
    #parameters
    self.inputSize = 3
    self.outputSize = 5
    self.hidden_layer_1_Size = 4
    self.hidden_layer_2_Size = 3
#https://docs.scipy.org/doc/numpy/reference/generated/numpy.full.html#numpy.full
    #weights
    self.W1 = np.full((self.inputSize, self.hidden_layer_1_Size), 0.05) #  weight matrix from input to hidden layer
    self.W2 = np.full((self.hidden_layer_1_Size, self.hidden_layer_2_Size), 0.025)
    self.W3 = np.full((self.hidden_layer_2_Size, self.outputSize), 1.0)# weight matrix from hidden to output layer

  def forward(self, X):
    #forward propagation through our network
    self.z = np.dot(X, self.W1) + b1 # dot product of X (input) and first set  weights
    self.z2 = self.sigmoid(self.z) # activation function
    self.z3 = np.dot(self.z2, self.W2) + b2
    self.z4 = self.sigmoid(self.z3)
    self.z5 = np.dot(self.z4, self.W3) + b3
    o = self.softmax(self.z5) # final activation function
    return o

  def sigmoid(self, s):
    # activation function
    return 1/(1+np.exp(-s))

  def softmax(self, x):
    """Compute softmax values for each sets of scores in x."""
    e_x = np.exp(x)
    return e_x / e_x.sum(axis=0)

NN = Neural_Network()

#defining our output
o = NN.forward(X)

print( "Predicted Output: \n" + str(o))


Predicted Output: 
[0.13239166 0.16999425 0.22946824 0.18787271 0.28027314]
